# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2ada7138e757b2d26bbbf64eb762792b492d2b2f049c3a8d957917e67e5de547b25d7c7874ed52682f0791e08851364259f007318502608cb7f73649fce54e8

test:
  secret_key_base: c0b459e360d2804883f44033845643bb3976beb61514b9ea7b49a4895d3f3830c336fec3ff54618515eb1b8d5d8b5524e42911cbf6dc8fc73fe44456392036b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
